---
# tasks file for apache
- name: Install Apache (Amazon Linux)
  yum:
    name: httpd
    state: present
  when: ansible_distribution == "Amazon"

- name: Install Apache (Ubuntu/Debian)
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Start Apache service
  service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: yes
...
