---
- name: under maintenance
  hosts: n2
  become: yes

  tasks:
    - name: Remove old web content
      file:
        path: /var/www/html
        state: absent

    - name: Update maintenance page
      copy:
        src: Maintenance.html
        dest: /var/www/html/index.html
