---
tasks:
  - name: Remove old web content
    file:
      path: /var/www/html
      state: absent

  - name: Recreate /var/www/html
    file:
      path: /var/www/html
      state: directory
      mode: '0755'

  - name: Update Static page
    copy:
      src: static.html
      dest: /var/www/html/static.html

  - name: Update Dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html

